### ISSUE TITLE
Font Awesome 5.0

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wp-menu-icons#130]
We should include Font Awesome 5.0 icons. @abaicus

**Comment by abaicus** [comment]
Yep, we should. Feel free to send in a PR if you want :D otherwise this should be easy to do by anyone on the development team.

**Comment by HardeepAsrani** [comment]
Should I just update the fonts or also update the classes used in the control.

**Comment by rohittm** [comment]
@HardeepAsrani @abaicus Seems like people really need it to be updated to FA5.0: https://wordpress.org/support/topic/need-update-after-fontawesome-5-0/

**Comment by HardeepAsrani** [comment]
@abaicus Where is the icon picker library? o.O

**Comment by rohittm** [comment]
@HardeepAsrani , I guess we are using it using composer.

**Comment by rohittm** [comment]
Also, I see this warning o.O

![screen shot 2018-03-09 at 12 35 16](https://user-images.githubusercontent.com/3204558/37194885-66dce45c-2396-11e8-827e-b579c54769c7.png)

**Comment by HardeepAsrani** [comment]
Yea, it's not ionutn/icon-picker now.

**Comment by rohittm** [comment]
Actually, https://github.com/ineagu/wp-icon-picker

**Comment by rohittm** [comment]
We should update our composer.json then

**Comment by selul** [comment]
@HardeepAsrani @rohittm there is not need to rush on this.

**Comment by ajtruckle** [comment]
What is the situation with this

**Comment by uproarink** [comment]
The latest version of Font Awesome is 5.1.  Is it very difficult to update this plugin to support the latest version?

**Comment by HardeepAsrani** [comment]
It's gonna be little complicated as Font Awesome 5, unfortunately, isn't Backward Compatible. 😞

**Comment by uproarink** [comment]
I was able to add support for the latest version of Font Awesome by adding the stylesheet to the theme.

I don’t understand the issue of backward compatibility since I am working with my own instance of Wordpress.

Let me know if you’re interested in how I did it.

William Leong
President
Uproar Ink

wleong@uproarink.com
(650) 283-2255 mobile
(510) 298-3553 office
________________________________

**Comment by ajtruckle** [comment]
All I know is that if I have "Better Font Awesome" installed (beta edition) and set it to the latest 5.x version that the meni-icons plugin no longer functions correctly and some icons are missing. Particularly the fab prefixed ones.

**Comment by HardeepAsrani** [comment]
@abaicus There has been menu requests for this. Any timeline on this? And if yes, are we adding FA5 as a separate font or update the older version?

**Comment by selul** [comment]
@HardeepAsrani this is not really a priority right now as our pipeline is pretty full, but any help is appreciated.

**Comment by poonam279** [comment]
People on wp.org forum asking about Font Awesome 5.0 icons. Are we going to implement this in near future?

**Comment by willgorham** [comment]
8 months later... it would certainly be nice to have a FA5 update please :)

**Comment by ajtruckle** [comment]
Yes. Ditto. 😀

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by cristian-ungureanu** [comment]
@girishpanchal30 let's evaluate a bit the complexity of adding FA5 here.

**Comment by girishpanchal30** [comment]
@cristian-ungureanu I have added font awesome 5 icons support and also added backward compatibility support in our existing icons.
Now users can add any new font awesome using the bellow filter.

function __icon_picker_fa_items( $icons ) {
  $icons[] = array(
    'group' => 'brand', // all, a11y, brand, chart, currency, directional, file-types, form-control, gender, medical, payment, spinner, transportation, text-editor, video-player, web-application
    'id'    => 'fab fa-elementor',
    'name'  => 'Elementor',
  );
  return $icons;
}
add_filter( 'icon_picker_fa_items', '__icon_picker_fa_items' );

Here is the list of free icons - https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free

Note: I have removed `tripadvisor` icon due to deprecated in fa5
Ref - https://fontawesome.com/v5.15/icons/tripadvisor

**Comment by ajtruckle** [comment]
Thanks for the update. At the moment the theme I am using has its own direct support for menu icons so I no longer require this plugin. But I appreciate your hard work!

**Comment by girishpanchal30** [comment]
@selul Fixed the CI checker issue, Please check here - https://github.com/Codeinwp/wp-menu-icons/pull/199
Thanks
