### ISSUE TITLE
recommend neve + otter

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/wp-menu-icons#194]
@selul I saw here we recommend advanced css, maybe we can redo that part and add some blocks where we mention some of our main products as cards + maybe if we want 2-3 tutorials that we think are relevant : https://vertis.d.pr/0r4LDH . 

Since that space is created by our plugin, I don't think we're messing with the user experience. Not sure if is worth considering a notice in the wp-admin/nav-menus.php that we recommend to use it with Neve.

**Comment by mghenciu** [comment]
Following up, as discussed on Slack.

I will start working on this, **with things to be done**:
- there is already a Card for Neve, which is visible when Neve is not activated
<img width="1360" alt="Screenshot 2021-11-17 at 15 55 10" src="https://user-images.githubusercontent.com/52494172/142213770-0001d8d6-9dc0-4672-a93c-a52195f9715b.png">

- we need to improve the Design for this card, make it scalable
- make a version of the same card with Otter, instead of Neve
- create also a version for Dashboard Notice, promoting Neve

Let me know if I missed something.
cc. @JohnPixle

**Comment by mghenciu** [comment]
[Here's the progress so far](https://www.figma.com/file/lfDtHB51hvKH0TBBIkJfZp/Menu-Icons?node-id=26%3A6):

- I've created 2 versions of **Dashboard notice**, and I think we can use them across products, not just for Menu Icons:
![image](https://user-images.githubusercontent.com/52494172/142632039-efa03bd9-f4e2-4161-9450-e2a7000e20b4.png)

- and 2 versions for the Preview Card (with & without a Thumbnail)

![Preview - Neve card v2](https://user-images.githubusercontent.com/52494172/142632371-83fd04ad-8403-4e63-9393-8da47617b081.png)
![Preview - Neve card v1](https://user-images.githubusercontent.com/52494172/142632362-d9ca6d6a-2df8-4657-8098-d81b1b0db0f2.png)
![Preview - Neve card v2-1](https://user-images.githubusercontent.com/52494172/142632367-6d9b1d4e-1ea2-49d0-a61b-852e075a1b60.png)

And about **recommending Otter**, I think we could use the same approach, but I incline towards using just one Card in this context. 
Why just one card? because we don't want to increase the Cognitive load too much (making it difficult for users to process too many cards, text, buttons). But we can have some kind of A/B, where A is Neve & B is Otter, and show those cards to different group of users.

Let me know your thoughts, when you have some time.
Thank you!

**Comment by ineagu** [comment]
for the dashboard notice is better without icon, to be less intrusive, while on the popup inserter is better with image because it gives more context and is a dedicated page.

**Comment by girishpanchal30** [comment]
@mghenciu Could you share the square image as shown below screenshot?

![image](https://user-images.githubusercontent.com/79647963/155527795-08b2b2f9-af08-43cd-a47e-2cf6afaac009.png)

**Comment by mghenciu** [comment]
> @mghenciu Could you share the square image as shown below screenshot?
> 

Sorry for that @girishpanchal30 , that's on me.
Now the acces should be fine.

**Comment by girishpanchal30** [comment]
@mghenciu Thank you
