### ISSUE TITLE
Notice recommending Neve keeps reappearing

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/wp-menu-icons#206]
After installing the plugin, there is a notice recommending Neve that appears on the dashboard and some users reported that it keeps reappearing after closing it and logging out of their accounts.

Reported here --> https://wordpress.org/support/topic/any-way-to-hide-theme-preview-message-forever/#post-15518527
https://wordpress.org/support/topic/thank-you-for-installing-menu-icons-any-way-to-hide-this-message-definitively/

**Comment by girishpanchal30** [comment]
Hello @MarinescuLucia

I can't reproduce this issue in my local system as well but now I have changed the hide notice method to solve this issue.
@selul I have removed the AJAX method to hide dashboard notice.

Please check and do let me know if you have any queries.

Thanks

**Comment by KZeni** [comment]
I'm still having this issue on the latest version of the plugin (0.12.12 via WP.org)

**Comment by KZeni** [comment]
I tested this by modifying the plugin code to use:
```
public static function wp_menu_icons_dismiss_dashboard_notice() {
	// Verify WP nonce and store hide notice flag.
	if ( isset( $_GET['_wp_notice_nonce'] ) && wp_verify_nonce( sanitize_text_field( wp_unslash( $_GET['_wp_notice_nonce'] ) ), self::DISMISS_NOTICE ) ) {
		set_transient( self::DISMISS_NOTICE, 1, 365 * DAY_IN_SECONDS );
		$transient_set = self::DISMISS_NOTICE.'=success';
	}else{
		$transient_set = self::DISMISS_NOTICE.'=failed-nonce';
	}
	if ( ! headers_sent() ) {
		wp_safe_redirect( admin_url().'?'.$transient_set );
		exit;
	}
}
```
to make sure the nonce check isn't the issue, and it redirected with `?menu-icons-dismiss-notice=success` appended to the resulting URL without issue.

What's interesting is that this appears to have made the dismissal of the notice stick! Even though this was done to help debug things, it appears this one edit has done the trick!

**Comment by KZeni** [comment]
It does appear to honor the notice being dismissed, but it appears relying on transients for this is just a bit unreliable. I use W3 Total Cache and purging caches also has transients be cleared as well (since they're used for the temporary storage of data). Transients can also be cleared out for any number of reasons. For example, I was simply refreshing to see the message return (didn't purge site cache or anything.)

As such, I think the most reliable way to honor the dismissal of this notice is to use a setting value instead of a transient.

**Comment by KZeni** [comment]
W3 Total cache does offer:

> Store transients in database
> _Use that to store transients in database even when external cache is used. That allows transient values to survive object cache cleaning / expiration_

as a checkbox under Object Cache settings, but the default is to have this be off.

Also, transients can be removed at any time by any number of reasons per it being given a "maximum lifetime" value with it not being a guarantee for the transient to be kept for that full duration (again, for any number of reasons where a plugin, the site itself, or something may clear out transient data.)

Going with a setting instead of transient for this would ensure it's not constantly bugging users of this plugin regardless of their setup. The setting stating the notice has been dismissed could actually be a timestamp of when it was dismissed (no other setting/value needed) so it can still re-show after a year or otherwise be cleared out if/when a new notice is to be shown just like a transient.

**Comment by girishpanchal30** [comment]
@selul Okay sure

**Comment by girishpanchal30** [comment]
@selul Now I have changed the transient API method to WP Option. Please check and do let me know if you have any queries.
Thanks

**Comment by selul** [comment]
@girishpanchal30 the default should be the transient value, otherwise they will get it another time.

**Comment by girishpanchal30** [comment]
@selul Thanks for checking, Now I have checked transient value as well.
Thanks
