### ISSUE TITLE
Deprecated warning when browsing the dashboard home

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/wp-menu-icons#270]
### Description

If you install Menu icons with PHP 8.1 and go to the dashboard home, there will be a deprecation warning in the Wordpress Guides/Tutorials widget that comes from our sdk https://vertis.d.pr/i/qMMHkM

User reported here - https://wordpress.org/support/topic/php-deprecated-automatic-conversion-of-false-to-array-is-deprecated-2

### Step-by-step reproduction instructions

1. Open a wordpress clean instance with PHP 8.1
2. Install Menu icons only (No Neve or other product)
3. Go to the dashboard home and check if the warning is visible

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/i/qMMHkM

### Environment info

WordPress 6.4.1 / PHP 8.1 / Menu Icons 0.13.7

### Is the issue you are reporting a regression

No

**Comment by preda-bogdan** [comment]
This was fixed since version 3.7 of the themeisle-sdk here: https://github.com/Codeinwp/themeisle-sdk/commit/9bbd9338013ab63f78397e431e1119929d1ffe6e

We only need to merge https://github.com/Codeinwp/wp-menu-icons/pull/269 in this PR and do a release.

cc: @vytisbulkevicius Let me know if you want me to do it.
